apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: retail
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: NodePort
  # Uncomment the line below to expose Mongo Express externally
  # nodePort: 30081
