apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: mongodb.uri
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: mongodb.database
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: order-service-secret
              key: mongodb.username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-service-secret
              key: mongodb.password
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: product.service.url
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: payment.service.url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
