apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: mongodb.uri
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: mongodb.database
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: payment-service-secret
              key: mongodb.username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-service-secret
              key: mongodb.password
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payment-service-secret
              key: stripe.secret.key
        - name: PAYPAL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: payment-service-secret
              key: paypal.client.id
        - name: PAYPAL_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-service-secret
              key: paypal.client.secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  type: ClusterIP
